### PR TITLE
Convert project to Python 3.6

### PR DESCRIPTION
**Pull request by john-soklaski**
This change converts the whole project to use Python 3.6.

I tested the decompilation and compilation fairly extensively and found them to be byte-for-byte the same with the Python 2 version. I'm unsure of a good way to test the upgrade functionality, do you have any ideas on that front?

Many of the changes are due to the different ways that Python 3 handles text and binary data, where Python 2 treats them to be much the same. Most notably I introduced a `astext` flag to the `resource_opener` lambdas. It is mostly used when dealing with `yml` and `txt` files.

- The file pickers in the UI are much better on Windows now.
- On Windows the compiler version is now Visual C++ 14.0.
- PyYAML doesn't yet have an official installer on Windows for Python 3.6, only 3.5. But, there is an unofficial binary wheel that works well for me.
- Boost is no longer required. I was having difficulty with the prebuilt boost windows binaries with Python 3. I believe they are [built incorrectly](https://sourceforge.net/p/boost/discussion/127795/thread/ce42a862/?limit=25#118d). I noticed that ccscript uses very little of boost::python's functionality, so I rewrote the single function that used boost to use the CPython api. I also used C++'s experimental::filesystem to replace boost::filesystem. I feel this makes the project easier to get started with.
- I have both ccscript and CCScriptWriter pointed to my own forks. I'd like to get your feedback on those changes as well (https://github.com/tripped/ccscript_legacy/compare/master...john-soklaski:master and https://github.com/Lyrositor/CCScriptWriter/compare/master...john-soklaski:master).

### CODE REVIEW

**Comment by john-soklaski** [comment]
I've now tested the cli interface under Ubuntu 16.04 via WSL and have it working great!

There are issues however with py2exe packaging. It doesn't seem to have been updated in a good while, so I'm checking out cx_freeze and pyinstaller as a substitute.

**Comment by mrtenda** [comment]
Amazing! Well done!

For testing the "Upgrade" functionality, I suggest downloading the earliest release of CoilSnake (they're all [here](https://github.com/mrtenda/CoilSnake/releases)), decompiling a ROM with that, then trying to use this version of CoilSnake to upgrade the project, and see if it compiles successfully.

Please let me know how things go with cx_freeze and pyinstaller. If the project switches over to one of those, maybe it will finally be possible to create a distributable Mac build of CoilSnake.

The changes to ccscript_legacy and CCScriptWriter look good to me too. It would probably be best to get those changes merged into their master branches before submitting this change to CoilSnake. I suggest you submit pull requests to those repositories directly. If the repository owners don't respond promptly please comment back here and I can contact them through outside means to get them to take a look.

**Comment by john-soklaski** [comment]
Thanks!

I tested "Upgrade" with v1.0 of CoilSnake and it is working well now. Just needed one small change to get it working.

I tried out both cx_freeze and pyinstaller. Pyinstaller seems to have problems with Python 3.6, but I was able to get cx_freeze working. I'll push those changes soon.

Thanks for taking a look my other changes, I'll issue those PRs to the other projects shortly.

**Comment by john-soklaski** [comment]
I switched it to package using cx_freeze and the creation of the NSIS installer works now. I also tested both Linux and Windows Vagrant configurations and they work (though the Windows image is x86 only).

**Comment by john-soklaski** [comment]
Can you hold off on merging this for right now? I discovered that if I compile a project which contains a decompiled script via the gui, it will hang for part of the process. It doesn't happen via the commandline, only the ui.

**Comment by mrtenda** [comment]
Sure, I'll wait until the issue is resolved

**Comment by john-soklaski** [comment]
It doesn't seem to be as big of a deal as I thought, I accidentally had Debug mode enabled :)

The extra logging (from eb.CccInterfaceModule) causes the ui to hang for the duration of the compilation, but it doesn't in the Python 2 version.

I'm still digging into it, but I don't think it is severe enough to block this as it only happens with debug logging.

**Comment by john-soklaski** [comment]
Since it's been a few days, would you mind contacting tripped so we can get https://github.com/tripped/ccscript_legacy/pull/6 merged?

**Comment by john-soklaski** [comment]
I fixed the ui hang issue with my latest commit. The issue was due to poor performance of ThreadSafeConsole under the load of thousands of lines of logging.

**Comment by mrtenda** [comment]
Looks like your ccscript changes were merged. Can you please change the reference in setup.py to point to the main repository?

**Comment by john-soklaski** [comment]
Thanks for contacting them! I've pointed it back to the original repo.

I think this PR should be all good to go now.

**Pull request merged**
