### PR TITLE
Added support to the TitleScreenModule to fix the debug menu kirby sprite

### PR DESCRIPTION
**Pull request by jamsilva**
This should fix issue #166. I did commit a minor sin by reading data from the ROM when writing but it was the best I could do considering that the data has to be moved and needs a specific memory placement.

### CODE REVIEW

**Comment by mrtenda** [comment]
Have you considered decompiling the Kirby sprite to an image in the CoilSnake project and then recompiling it back in? I think that would be the technically "correct" way of implementing this, since you wouldn't have to read from the ROM when writing. Reading from the ROM while writing is generally dangerous, because you don't know if the base ROM is a clean ROM or not.

**Comment by ShadowOne333** [comment]
If it helps, this is the code I am using in my MaternalBound Redux hack to repoint the Kirby graphics (this are ONLY the graphics). Let me know if you need any additional information to implement this into CoilSnake.

```
/* Repoint Kirby's graphics (just for fun) */
ROM[0xEFE55E] = ASMLoadAddress0E(kirby)
// Full pointer [A9 B7 EF 85 0E A9 EF 00 85 10]

kirby:	// Original offset 0xEFEFB7 - 0xEFF0D6
	"[00 00 00 00 00 00 01 00 02 01 03 00 05 00 0B 04 00 00 00 00 00 00 00 00 00 00 01 00 03 00 03 00 00 00 3E 00 D5 36 3E 80 FF 00 FF 00 9F 60 9F 60 00 00 00 00 08 00 7F 00 FF 00 FF 00 FF 00 FF 00 00 00 00 00 80 00 40 80 A0 40 E0 00 F0 20 E8 10 00 00 00 00 00 00 00 00 80 00 C0 00 C0 00 E0 00 0B 00 17 08 1F 08 15 00 1F 0A 16 08 0F 05 06 01 07 00 07 00 07 00 0F 00 05 00 05 00 00 00 00 00 FF 00 FF 00 EB 14 1C 00 DD C1 FF 00 FF 00 7F 00 FF 00 EB 00 FF 00 EB 00 2A 00 FF 00 FF 00 F7 00 E8 00 F4 08 FC 08 54 00 FC A8 B4 08 F8 50 30 40 F0 00 F0 00 F0 00 F8 00 50 00 D0 00 80 00 80 00 03 00 05 03 07 03 04 03 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3E 80 D5 36 7F 80 E3 00 80 00 00 00 00 00 00 00 7F 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 60 80 D0 60 70 E0 90 60 E0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00]"
```

**Comment by jamsilva** [comment]
Sorry for the long wait. I want to clarify that what I am moving in not the graphics but rather the assembly code and changing the pointer to direct to the new location. Because it is code I was expecting it to be at the original location in most (if not all) ROMs, including edited ones. Is there any other place where CoilSnake decompiles and recompiles assembly that you could point me to @mrtenda?

**Comment by mrtenda** [comment]
OK, I understand what it's doing now. Sorry, I should have looked at it more closely before.

Is there a reason that `KIRBY_INDEX_AND_ASM_OFFSET` is hardcoded like it is? Making it instead be read from the rom using `KIRBY_INDEX_AND_ASM_POINTER` seems like it'd be more robust, though I guess it's not necessary since CoilSnake won't be removing the old ASM in that location.

Also, did you test this out?

**Comment by jamsilva** [comment]
I did test it with a beta version of MaternalBound Redux, @ShadowOne333's hack, when making this patch and it worked well. I'll look into using one pointer to look up the other instead of having both hardcoded.

**Comment by jamsilva** [comment]
@mrtenda I think this is ready now :smile:. Let me know if you need any more changes.

**Comment by mrtenda** [comment]
Looks good to me! Thank you very much for fixing this

**Pull request merged**
